import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
// `java` in a Kotlin build script resolves to the Gradle extension, not the package.
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
}

/**
 * The desktop OAuth client secret, baked in at build time.
 *
 * DesktopOAuthConfig resolves the secret at runtime from the environment or `local.properties`,
 * which covers development but leaves a packaged app with nothing: the end user has neither. So
 * the same value is also compiled in here, as the last fallback in that chain.
 *
 * Read from `NOTELIKEUS_OAUTH_CLIENT_SECRET`, or `notelikeus.oauthClientSecret` in the gitignored
 * `local.properties`. Absent (CI, a fresh clone) it compiles to an empty string and only desktop
 * Google sign-in is unavailable — everything else builds and tests normally.
 *
 * Note this puts the secret in the shipped binary. Google classes installed-app secrets as
 * non-confidential (RFC 8252 — PKCE is what secures this flow), so that is the accepted trade;
 * what matters is that it stays out of version control.
 */
val oauthClientSecret: String =
    System.getenv("NOTELIKEUS_OAUTH_CLIENT_SECRET")
        ?: rootProject.file("local.properties").takeIf { it.exists() }?.let { file ->
            Properties()
                .apply { file.inputStream().use { stream -> load(stream) } }
                .getProperty("notelikeus.oauthClientSecret")
        }
        ?: ""

val generateDesktopSecrets by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/desktopSecrets/kotlin")
    val secret = oauthClientSecret
    inputs.property("oauthClientSecret", secret)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().asFile.resolve("com/aus/notelikeus/di/DesktopSecrets.kt")
        file.parentFile.mkdirs()
        // Escape so a quote/backslash in the environment variable cannot break the generated
        // Kotlin (or smuggle code into it) — the build must fail loudly on weird input instead.
        val escapedSecret = secret.replace("\\", "\\\\").replace("\"", "\\\"")
        file.writeText(
            """
            // Generated by the `generateDesktopSecrets` Gradle task. Do not edit or commit.
            package com.aus.notelikeus.di

            internal object DesktopSecrets {
                const val OAUTH_CLIENT_SECRET: String = "$escapedSecret"
            }

            """.trimIndent()
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    jvm("desktop")
    
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.animation)
                implementation(compose.components.resources)
                implementation(compose.components.uiToolingPreview)
                implementation(compose.materialIconsExtended)
                
                implementation(libs.koin.core)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)

                implementation(libs.compose.lifecycle.runtime)
                implementation(libs.compose.lifecycle.viewmodel)
                
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.room.runtime)
                implementation(libs.androidx.sqlite)
                implementation(libs.androidx.datastore.preferences.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.okio)
                
                implementation(libs.compose.navigation)
                
                implementation(libs.compose.material3.windowSizeClass)
                implementation(libs.compose.adaptive)
                implementation(libs.compose.adaptive.layout)
                implementation(libs.compose.adaptive.navigation)
            }
        }
        
        val androidMain by getting {
            dependencies {
                implementation(libs.androidx.activity.compose)
                implementation(libs.androidx.core.ktx)
                implementation(libs.androidx.lifecycle.runtime.ktx)
                implementation(libs.androidx.lifecycle.viewmodel.compose)
                implementation(libs.kotlinx.coroutines.android)
                implementation(libs.koin.android)
                implementation(libs.androidx.biometric)
                implementation(libs.androidx.datastore.preferences.android)
                implementation(project.dependencies.platform(libs.firebase.bom))
                implementation(libs.firebase.auth)
                implementation(libs.firebase.firestore)
                implementation(libs.firebase.appcheck.playintegrity)
                implementation(libs.play.services.auth)
                implementation(libs.kotlinx.coroutines.play.services)
                implementation(libs.androidx.credentials)
                implementation(libs.androidx.credentials.play.services.auth)
                implementation(libs.google.identity.googleid)
                implementation(libs.androidx.work.runtime.ktx)
                implementation(libs.sqlcipher.android)
                implementation(libs.androidx.security.crypto)
                implementation(libs.androidx.glance.appwidget)
            }
        }

        val androidUnitTest by getting {
            dependencies {
                implementation(libs.junit)
                implementation(libs.mockk)
                implementation(libs.robolectric)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.turbine)
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }
        
        val desktopMain by getting {
            kotlin.srcDir(generateDesktopSecrets)
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.androidx.sqlite.bundled)
                implementation(libs.jna)
                implementation(libs.jna.platform)
            }
        }

        val desktopTest by getting {
            dependencies {
                implementation(compose.desktop.uiTestJUnit4)
            }
        }
    }
}

android {
    namespace = "com.aus.notelikeus.shared"
    compileSdk = 37
    defaultConfig {
        minSdk = 26
    }
    buildFeatures {
        buildConfig = true
    }

    testOptions {
        unitTests {
            // Robolectric otherwise runs against a stub manifest, so Firebase's component discovery
            // finds no registrars and FirebaseFirestore.getInstance() fails with "Firestore
            // component is not present" — which is what FirestoreNoteTransportEmulatorTest needs.
            isIncludeAndroidResources = true
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.aus.notelikeus.MainKt"

        nativeDistributions {
            // Windows only. DesktopTokenStore encrypts the session with DPAPI through JNA
            // (Crypt32), which compiles everywhere but throws UnsatisfiedLinkError on first use
            // on macOS/Linux — so shipping Dmg and Deb produced installers whose sign-in could
            // not work. Restore those formats alongside a Keychain/libsecret backend.
            targetFormats(TargetFormat.Msi)
            packageName = "Notelikeus"
            packageVersion = "1.0.0"
            description = "Elite Cross-Platform Note Taking"
            copyright = "© 2026 Aus"
            vendor = "Aus"

            // jlink builds the packaged runtime from this list, so anything reached only
            // reflectively has to be named explicitly. All four fail *only* in the MSI —
            // `./gradlew run` has the full JDK on hand and hides every one of them.
            // jlink builds the packaged runtime from this list. Without it the image resolves to
            // 7 modules and omits the first three below, so the MSI fails at runtime while
            // `./gradlew run` — which has the whole JDK on hand — stays green. Verified by
            // diffing `runtime/release` in the generated app image with and without this block.
            modules(
                "java.net.http",    // HttpClient: Firestore transport, token refresh, sign-in
                "jdk.unsupported",  // sun.misc.Unsafe, via datastore-protobuf
                "java.naming",      // reached from the TLS stack
                // Present by default on the current JDK, named anyway so a JDK change cannot
                // silently drop EC and break the handshake with accounts.google.com.
                "jdk.crypto.ec"
            )

            windows {
                shortcut = true
                menu = true
                upgradeUuid = "d738f712-4217-485c-9c71-0816999b7082"
            }
        }
    }
}

room {
    schemaDirectory("$projectDir/schemas")
}

dependencies {
    add("kspAndroid", libs.room.compiler)
    add("kspDesktop", libs.room.compiler)
}
