# Generate web/.env from Firebase CLI (not committed).
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$WebAppId = "1:404285880902:web:6a84257413e7552c996847"
$GoogleClientId = "404285880902-cpiu3nj2itndnh0kkouvn374ec5ecl9v.apps.googleusercontent.com"
$OutPath = Join-Path $ProjectRoot "web\.env"
$TempJson = Join-Path $env:TEMP "notelikeus-web-sdk.json"

Push-Location $ProjectRoot
try {
    firebase apps:sdkconfig WEB $WebAppId --project notelikeus --out $TempJson | Out-Null
    $config = Get-Content $TempJson -Raw | ConvertFrom-Json

    @"
# Generated by scripts/setup-web-env.ps1 — do not commit.
VITE_FIREBASE_API_KEY=$($config.apiKey)
VITE_FIREBASE_AUTH_DOMAIN=$($config.authDomain)
VITE_FIREBASE_PROJECT_ID=$($config.projectId)
VITE_FIREBASE_STORAGE_BUCKET=$($config.storageBucket)
VITE_FIREBASE_MESSAGING_SENDER_ID=$($config.messagingSenderId)
VITE_FIREBASE_APP_ID=$($config.appId)
VITE_FIREBASE_GOOGLE_CLIENT_ID=$GoogleClientId
"@ | Set-Content -Path $OutPath -Encoding utf8

    Write-Host "Wrote $OutPath"
} finally {
    Pop-Location
    if (Test-Path $TempJson) { Remove-Item $TempJson -Force }
}
